# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
# electron 8.8 GeV,  direction (0.,0.,1.)
#
/gun/particle e-
/gun/energy 8.8 GeV
/tracking/verbose 0
#
/run/beamOn 1
